default:
  configuration:
    input: /docs_tests/input
    output: ./docs_tests/output
  frontmatter:
    category:
      default value: notes
      key: category
    index: (i)
    share: share
  weblink: cc
minimal:
  configuration:
    input: null
    output: null
  frontmatter:
    category:
      default value: notes
      key: category
    index: (i)
    share: share
  weblink: null
northword:
  configuration:
    input: ./src
    output: ./docs
  frontmatter:
    category:
      default value: notes
      key: category
    index: (i)
    share: share
  weblink: null
